### ISSUE TITLE
v1.18.4 is missing the `dist/` folder

### ISSUE THREAD

**Issue by jeremybanka** [mendableai/firecrawl#1273]
**Describe the Bug**
Version 1.18.4 is not usable. The `dist/` folder is missing in the package.

**To Reproduce**
Steps to reproduce the issue:
```sh
mkdir repro-missing-firecrawl
cd repro-missing-firecrawl
npm i @mendable/firecrawl-js typescript
echo "import Firecrawl from '@mendable/firecrawl-js'" > main.ts
./node_modules/.bin/tsc main.ts
```

This will result in

```
main.ts:1:23 - error TS2307: Cannot find module '@mendable/firecrawl-js' or its corresponding type declarations.
```

Confirm here—there is no dist folder in the latest version: https://www.npmjs.com/package/@mendable/firecrawl-js/v/1.18.4?activeTab=code

**Expected Behavior**
`dist/` folder is built and deployed with all new versions of firecrawl. 

**Screenshots**
(none)

**Environment (please complete the following information):**
- OS: Darwin 24.3.0 arm64 arm
- Firecrawl Version: 1.18.4
- Node.js Version: v23.9.0

**Logs**
(none)

**Additional Context**
(none)

**Comment by nickscamara** [comment]
Hey @jeremybanka sorry about that, we just pushed a patch fix. Should be working in 1.18.5 now!
