### ISSUE TITLE
[Bug] 1.18.4 @mendable/firecrawl-js NPM package missing dist directory

### ISSUE THREAD

**Issue by b0o** [mendableai/firecrawl#1272]
**Describe the Bug**
Version 1.18.4 of @mendable/firecrawl-js published to NPM is missing the dist directory, resulting in errors like this:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'node_modules/@mendable/firecrawl-js/dist/index.js'
```
```
$ ls -1 node_modules/@mendable/firecrawl-js
node_modules/
src/
.env.example
jest.config.js
LICENSE
package.json
README.md
tsconfig.json
tsup.config.ts
```

**Comment by nickscamara** [comment]
Hey @b0o  sorry about that, we just pushed a patch fix. Should be working in 1.18.5 now!
